# Generated by Django 5.2.7 on 2025-10-27 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('facilities', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Calendario', max_length=80)),
                ('duracion_bloque_min', models.PositiveSmallIntegerField(default=45)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='academics.periodo')),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_min', models.PositiveSmallIntegerField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='scheduling.calendario')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ('calendario', 'orden'),
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Teoría'), ('P', 'Práctica')], max_length=1)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('bloques_duracion', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='propuesto', max_length=12)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='facilities.ambiente')),
                ('bloque_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_inicio', to='scheduling.bloque')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='users.docente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academics.grupo')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='CambioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('old_day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
                ('old_bloques_duracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
                ('new_bloques_duracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_new_ambiente', to='facilities.ambiente')),
                ('new_bloque_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_new_inicio', to='scheduling.bloque')),
                ('new_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_new_docente', to='users.docente')),
                ('old_ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_old_ambiente', to='facilities.ambiente')),
                ('old_bloque_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_old_inicio', to='scheduling.bloque')),
                ('old_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_old_docente', to='users.docente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_horario', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='scheduling.clase')),
            ],
            options={
                'verbose_name': 'Cambio de Horario',
                'verbose_name_plural': 'Cambios de Horario',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='ConflictoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOCENTE', 'Docente'), ('AMBIENTE', 'Ambiente'), ('GRUPO', 'Grupo')], max_length=8)),
                ('resuelto', models.BooleanField(default=False)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('detectado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('clase_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos_como_a', to='scheduling.clase')),
                ('clase_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos_como_b', to='scheduling.clase')),
            ],
            options={
                'verbose_name': 'Conflicto de Horario',
                'verbose_name_plural': 'Conflictos de Horario',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('bloques_duracion', models.PositiveSmallIntegerField(default=1)),
                ('preferencia', models.IntegerField(default=0)),
                ('bloque_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades_inicio', to='scheduling.bloque')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_docente', to='scheduling.calendario')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='users.docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad Docente',
                'verbose_name_plural': 'Disponibilidades Docentes',
            },
        ),
        migrations.AddIndex(
            model_name='bloque',
            index=models.Index(fields=['calendario', 'orden'], name='scheduling__calenda_3815c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloque',
            constraint=models.UniqueConstraint(fields=('calendario', 'orden'), name='bloque_orden_unico_por_calendario'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['day_of_week', 'bloque_inicio'], name='scheduling__day_of__932543_idx'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['docente', 'day_of_week', 'bloque_inicio'], name='scheduling__docente_a16f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['ambiente', 'day_of_week', 'bloque_inicio'], name='scheduling__ambient_aef2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['grupo', 'day_of_week', 'bloque_inicio'], name='scheduling__grupo_i_1a59ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(fields=('grupo', 'day_of_week', 'bloque_inicio'), name='clase_unica_por_grupo_dia_bloque'),
        ),
        migrations.AddIndex(
            model_name='conflictohorario',
            index=models.Index(fields=['tipo', 'resuelto'], name='scheduling__tipo_0febc4_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictohorario',
            index=models.Index(fields=['clase_a'], name='scheduling__clase_a_13c122_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictohorario',
            index=models.Index(fields=['clase_b'], name='scheduling__clase_b_33952c_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidaddocente',
            index=models.Index(fields=['docente', 'calendario', 'day_of_week'], name='scheduling__docente_a39703_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidaddocente',
            index=models.Index(fields=['bloque_inicio'], name='scheduling__bloque__1433b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidaddocente',
            constraint=models.UniqueConstraint(fields=('docente', 'calendario', 'day_of_week', 'bloque_inicio'), name='disp_docente_unica_por_cal_dia_bloque'),
        ),
    ]
