# Generated by Django 5.2.7 on 2025-11-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_clase_docente'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='docente_substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases_substituto', to='users.docente'),
        ),
    ]
