# Generated by Django 5.2.7 on 2025-10-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('carga_min_semanal', models.PositiveSmallIntegerField(default=0)),
                ('carga_max_semanal', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'constraints': [models.CheckConstraint(condition=models.Q(('carga_max_semanal__gte', models.F('carga_min_semanal'))), name='docente_carga_max_ge_min')],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'indexes': [models.Index(fields=['matricula'], name='users_estud_matricu_c2fde3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('JEFE_CARRERA', 'Jefe de Carrera'), ('VICERRECTORADO', 'Vicerrectorado'), ('RECTOR', 'Rector'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20)),
                ('permisos', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'indexes': [models.Index(fields=['role'], name='users_userp_role_c31a7e_idx')],
            },
        ),
    ]
