# Generated by Django 5.2.7 on 2025-10-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Ambiente',
                'verbose_name_plural': 'Tipos de Ambiente',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'indexes': [models.Index(fields=['codigo'], name='facilities__codigo_5fe173_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('capacidad', models.PositiveIntegerField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='facilities.edificio')),
                ('tipo_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambientes', to='facilities.tipoambiente')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'indexes': [models.Index(fields=['tipo_ambiente'], name='facilities__tipo_am_69de55_idx'), models.Index(fields=['capacidad'], name='facilities__capacid_f7f313_idx')],
                'constraints': [models.UniqueConstraint(fields=('edificio', 'codigo'), name='ambiente_codigo_unico_por_edificio')],
            },
        ),
    ]
