# Generated by Django 5.2.7 on 2025-10-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Ambiente',
                'verbose_name_plural': 'Tipos de Ambiente',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras_dirigidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('horas_teoria_semana', models.PositiveSmallIntegerField(default=0)),
                ('horas_practica_semana', models.PositiveSmallIntegerField(default=0)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academics.carrera')),
                ('tipo_ambiente_practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_practica', to='academics.tipoambiente')),
                ('tipo_ambiente_teoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_teoria', to='academics.tipoambiente')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.PositiveIntegerField(help_text='Año, p.ej. 2025')),
                ('numero', models.PositiveSmallIntegerField(help_text='1 o 2')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'constraints': [models.UniqueConstraint(fields=('gestion', 'numero'), name='periodo_gestion_numero_unico')],
            },
        ),
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='academics.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='users.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='academics.periodo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscripciones', to='academics.turno')),
            ],
            options={
                'verbose_name': 'Preinscripción',
                'verbose_name_plural': 'Preinscripciones',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('capacidad', models.PositiveIntegerField(default=40)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('cerrado', 'Cerrado')], default='borrador', max_length=12)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academics.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='users.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academics.periodo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academics.turno')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='users.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academics.grupo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'indexes': [models.Index(fields=['estudiante'], name='academics_i_estudia_ee0317_idx'), models.Index(fields=['grupo'], name='academics_i_grupo_i_5346ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'estudiante'), name='inscripcion_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('carrera', 'codigo'), name='asignatura_codigo_unico_por_carrera'),
        ),
        migrations.AddIndex(
            model_name='preinscripcion',
            index=models.Index(fields=['periodo', 'asignatura', 'turno'], name='academics_p_periodo_a1434e_idx'),
        ),
        migrations.AddConstraint(
            model_name='preinscripcion',
            constraint=models.UniqueConstraint(fields=('periodo', 'asignatura', 'turno', 'estudiante'), name='preinscripcion_unica'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['periodo', 'asignatura', 'turno'], name='academics_g_periodo_c029d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('asignatura', 'periodo', 'codigo'), name='grupo_unico_por_asig_periodo_cod'),
        ),
    ]
