# Generated by Django 5.2.7 on 2025-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_grupo_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
